spring:
  application:
    name: restaurant-ordering-system

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always